package model;
// Generated 25/03/2021 09:05:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private int id;
     private Departamento departamento;
     private String descripcion;
     private Integer estado;
     private Set usuarios = new HashSet(0);

    public Ciudad() {
    }

	
    public Ciudad(int id, Departamento departamento) {
        this.id = id;
        this.departamento = departamento;
    }
    public Ciudad(int id, Departamento departamento, String descripcion, Integer estado, Set usuarios) {
       this.id = id;
       this.departamento = departamento;
       this.descripcion = descripcion;
       this.estado = estado;
       this.usuarios = usuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


