package model;
// Generated 25/03/2021 09:05:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set ciudads = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int id) {
        this.id = id;
    }
    public Departamento(int id, String descripcion, Set ciudads) {
       this.id = id;
       this.descripcion = descripcion;
       this.ciudads = ciudads;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }




}


