package model;
// Generated 25/03/2021 09:05:30 PM by Hibernate Tools 4.3.1



/**
 * EstadoAprobacionTienda generated by hbm2java
 */
public class EstadoAprobacionTienda  implements java.io.Serializable {


     private int id;
     private Tienda tienda;
     private Byte tiendaEstaAprobada;
     private String observaciones;

    public EstadoAprobacionTienda() {
    }

	
    public EstadoAprobacionTienda(int id, Tienda tienda) {
        this.id = id;
        this.tienda = tienda;
    }
    public EstadoAprobacionTienda(int id, Tienda tienda, Byte tiendaEstaAprobada, String observaciones) {
       this.id = id;
       this.tienda = tienda;
       this.tiendaEstaAprobada = tiendaEstaAprobada;
       this.observaciones = observaciones;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tienda getTienda() {
        return this.tienda;
    }
    
    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }
    public Byte getTiendaEstaAprobada() {
        return this.tiendaEstaAprobada;
    }
    
    public void setTiendaEstaAprobada(Byte tiendaEstaAprobada) {
        this.tiendaEstaAprobada = tiendaEstaAprobada;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


