package model;
// Generated 25/03/2021 09:05:30 PM by Hibernate Tools 4.3.1



/**
 * EstadoAprobacionRolUsuario generated by hbm2java
 */
public class EstadoAprobacionRolUsuario  implements java.io.Serializable {


     private int id;
     private RolUsuario rolUsuario;
     private Byte rolEstaAprobado;
     private String observaciones;

    public EstadoAprobacionRolUsuario() {
    }

	
    public EstadoAprobacionRolUsuario(int id, RolUsuario rolUsuario) {
        this.id = id;
        this.rolUsuario = rolUsuario;
    }
    public EstadoAprobacionRolUsuario(int id, RolUsuario rolUsuario, Byte rolEstaAprobado, String observaciones) {
       this.id = id;
       this.rolUsuario = rolUsuario;
       this.rolEstaAprobado = rolEstaAprobado;
       this.observaciones = observaciones;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public RolUsuario getRolUsuario() {
        return this.rolUsuario;
    }
    
    public void setRolUsuario(RolUsuario rolUsuario) {
        this.rolUsuario = rolUsuario;
    }
    public Byte getRolEstaAprobado() {
        return this.rolEstaAprobado;
    }
    
    public void setRolEstaAprobado(Byte rolEstaAprobado) {
        this.rolEstaAprobado = rolEstaAprobado;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


