package model;
// Generated 25/03/2021 09:05:30 PM by Hibernate Tools 4.3.1



/**
 * FotoProducto generated by hbm2java
 */
public class FotoProducto  implements java.io.Serializable {


     private int id;
     private Producto producto;
     private String enlace;

    public FotoProducto() {
    }

	
    public FotoProducto(int id, Producto producto) {
        this.id = id;
        this.producto = producto;
    }
    public FotoProducto(int id, Producto producto, String enlace) {
       this.id = id;
       this.producto = producto;
       this.enlace = enlace;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getEnlace() {
        return this.enlace;
    }
    
    public void setEnlace(String enlace) {
        this.enlace = enlace;
    }




}


