package model;
// Generated 25/03/2021 09:05:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int id;
     private Tienda tienda;
     private String nombre;
     private String descripcion;
     private String categoria;
     private Integer cantidad;
     private Integer precio;
     private Set fotoProductos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int id, Tienda tienda) {
        this.id = id;
        this.tienda = tienda;
    }
    public Producto(int id, Tienda tienda, String nombre, String descripcion, String categoria, Integer cantidad, Integer precio, Set fotoProductos) {
       this.id = id;
       this.tienda = tienda;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.categoria = categoria;
       this.cantidad = cantidad;
       this.precio = precio;
       this.fotoProductos = fotoProductos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tienda getTienda() {
        return this.tienda;
    }
    
    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Set getFotoProductos() {
        return this.fotoProductos;
    }
    
    public void setFotoProductos(Set fotoProductos) {
        this.fotoProductos = fotoProductos;
    }




}


