package model;
// Generated 25/03/2021 09:05:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set rolUsuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(int id) {
        this.id = id;
    }
    public Rol(int id, String descripcion, Set rolUsuarios) {
       this.id = id;
       this.descripcion = descripcion;
       this.rolUsuarios = rolUsuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getRolUsuarios() {
        return this.rolUsuarios;
    }
    
    public void setRolUsuarios(Set rolUsuarios) {
        this.rolUsuarios = rolUsuarios;
    }




}


