package model;
// Generated 25/03/2021 09:05:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tienda generated by hbm2java
 */
public class Tienda  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String nombre;
     private String direccion;
     private String ubicacionGps;
     private String telefono;
     private String horarioAtencion;
     private Set estadoAprobacionTiendas = new HashSet(0);
     private Set productos = new HashSet(0);

    public Tienda() {
    }

	
    public Tienda(int id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public Tienda(int id, Usuario usuario, String nombre, String direccion, String ubicacionGps, String telefono, String horarioAtencion, Set estadoAprobacionTiendas, Set productos) {
       this.id = id;
       this.usuario = usuario;
       this.nombre = nombre;
       this.direccion = direccion;
       this.ubicacionGps = ubicacionGps;
       this.telefono = telefono;
       this.horarioAtencion = horarioAtencion;
       this.estadoAprobacionTiendas = estadoAprobacionTiendas;
       this.productos = productos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getUbicacionGps() {
        return this.ubicacionGps;
    }
    
    public void setUbicacionGps(String ubicacionGps) {
        this.ubicacionGps = ubicacionGps;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getHorarioAtencion() {
        return this.horarioAtencion;
    }
    
    public void setHorarioAtencion(String horarioAtencion) {
        this.horarioAtencion = horarioAtencion;
    }
    public Set getEstadoAprobacionTiendas() {
        return this.estadoAprobacionTiendas;
    }
    
    public void setEstadoAprobacionTiendas(Set estadoAprobacionTiendas) {
        this.estadoAprobacionTiendas = estadoAprobacionTiendas;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


