package model;
// Generated 25/03/2021 09:05:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumentoIdentidad generated by hbm2java
 */
public class TipoDocumentoIdentidad  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set usuarios = new HashSet(0);

    public TipoDocumentoIdentidad() {
    }

	
    public TipoDocumentoIdentidad(int id) {
        this.id = id;
    }
    public TipoDocumentoIdentidad(int id, String descripcion, Set usuarios) {
       this.id = id;
       this.descripcion = descripcion;
       this.usuarios = usuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


