package model;
// Generated 25/03/2021 09:05:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private Ciudad ciudad;
     private TipoDocumentoIdentidad tipoDocumentoIdentidad;
     private String nombres;
     private String apellidos;
     private String numeroDocumentoIdentidad;
     private String telefono;
     private String celular;
     private String email;
     private String nickname;
     private String contrasena;
     private String direccion;
     private String detalleDireccion;
     private String ubicacionGps;
     private String copiaRut;
     private String copiaDocumentoIdentidad;
     private Byte usuarioEstaActivo;
     private Set tiendas = new HashSet(0);
     private Set rolUsuarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, Ciudad ciudad, TipoDocumentoIdentidad tipoDocumentoIdentidad, String nombres, String apellidos, String numeroDocumentoIdentidad, String celular, String email, String nickname, String contrasena) {
        this.id = id;
        this.ciudad = ciudad;
        this.tipoDocumentoIdentidad = tipoDocumentoIdentidad;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
        this.celular = celular;
        this.email = email;
        this.nickname = nickname;
        this.contrasena = contrasena;
    }
    public Usuario(int id, Ciudad ciudad, TipoDocumentoIdentidad tipoDocumentoIdentidad, String nombres, String apellidos, String numeroDocumentoIdentidad, String telefono, String celular, String email, String nickname, String contrasena, String direccion, String detalleDireccion, String ubicacionGps, String copiaRut, String copiaDocumentoIdentidad, Byte usuarioEstaActivo, Set tiendas, Set rolUsuarios) {
       this.id = id;
       this.ciudad = ciudad;
       this.tipoDocumentoIdentidad = tipoDocumentoIdentidad;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
       this.telefono = telefono;
       this.celular = celular;
       this.email = email;
       this.nickname = nickname;
       this.contrasena = contrasena;
       this.direccion = direccion;
       this.detalleDireccion = detalleDireccion;
       this.ubicacionGps = ubicacionGps;
       this.copiaRut = copiaRut;
       this.copiaDocumentoIdentidad = copiaDocumentoIdentidad;
       this.usuarioEstaActivo = usuarioEstaActivo;
       this.tiendas = tiendas;
       this.rolUsuarios = rolUsuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public TipoDocumentoIdentidad getTipoDocumentoIdentidad() {
        return this.tipoDocumentoIdentidad;
    }
    
    public void setTipoDocumentoIdentidad(TipoDocumentoIdentidad tipoDocumentoIdentidad) {
        this.tipoDocumentoIdentidad = tipoDocumentoIdentidad;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNumeroDocumentoIdentidad() {
        return this.numeroDocumentoIdentidad;
    }
    
    public void setNumeroDocumentoIdentidad(String numeroDocumentoIdentidad) {
        this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDetalleDireccion() {
        return this.detalleDireccion;
    }
    
    public void setDetalleDireccion(String detalleDireccion) {
        this.detalleDireccion = detalleDireccion;
    }
    public String getUbicacionGps() {
        return this.ubicacionGps;
    }
    
    public void setUbicacionGps(String ubicacionGps) {
        this.ubicacionGps = ubicacionGps;
    }
    public String getCopiaRut() {
        return this.copiaRut;
    }
    
    public void setCopiaRut(String copiaRut) {
        this.copiaRut = copiaRut;
    }
    public String getCopiaDocumentoIdentidad() {
        return this.copiaDocumentoIdentidad;
    }
    
    public void setCopiaDocumentoIdentidad(String copiaDocumentoIdentidad) {
        this.copiaDocumentoIdentidad = copiaDocumentoIdentidad;
    }
    public Byte getUsuarioEstaActivo() {
        return this.usuarioEstaActivo;
    }
    
    public void setUsuarioEstaActivo(Byte usuarioEstaActivo) {
        this.usuarioEstaActivo = usuarioEstaActivo;
    }
    public Set getTiendas() {
        return this.tiendas;
    }
    
    public void setTiendas(Set tiendas) {
        this.tiendas = tiendas;
    }
    public Set getRolUsuarios() {
        return this.rolUsuarios;
    }
    
    public void setRolUsuarios(Set rolUsuarios) {
        this.rolUsuarios = rolUsuarios;
    }
    
    

    


    

}


